# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  ci:
    name: Vet, Lint, Test and Vulnerability Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.21.0"

    - name: Vet
      run: make vet

    # the official golanci-lint-action logs a lot of errors (https://github.com/golangci/golangci-lint-action/issues/135)
    # therefore it's replaced with a manual approach
    # - name: Lint
    #   uses: golangci/golangci-lint-action@v3

    # there is an currently an issue with "enforce-repeated-arg-type-style".
    # we should probably be able the latest version when golangci-lint v1.56.1 is released.
    # https://github.com/golangci/golangci-lint/issues/4353

    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        golangci-lint run --out-format=github-actions

    - name: Vulnerability Check
      uses: golang/govulncheck-action@v1
      with:
        go-package: ./...
        go-version-input: ">=1.21.0"
        check-latest: true

    - name: Integration Tests
      run: make test_integration
    
    - name: Recovery Tests
      run: make test_recovery

    
