# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  ci:
    name: Vet, Lint, Test and Vulnerability Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.22.4"

    - name: Vet
      run: make vet

    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
        golangci-lint run --out-format=github-actions

    - name: Vulnerability Check
      uses: golang/govulncheck-action@v1
      with:
        go-package: ./...
        go-version-input: ">=1.22.4"
        check-latest: true

    - name: Integration Tests
      run: make test_integration
    
    - name: Recovery Tests
      run: make test_recovery

    
